apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guest-book
    tier: frontend
spec:
  ports:
  - port: 80
  selector:
    app: guest-book
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guest-book
spec:
  selector:
    matchLabels:
      app: guest-book
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: guest-book
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
