apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: guest-book
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: guest-book
    tier: redis
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: redis-pv-claim
  labels:
    app: guest-book
spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: guest-book
spec:
  selector:
    matchLabels:
      app: guest-book
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: guest-book
        tier: redis
    spec:
      containers:
      - image: redis:5.0.5
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /var/lib/redis
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim
