apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin-demo
  labels:
    app: openldap-demo
    tier: phpldapadmin-demo
spec:
  ports:
  - port: 443
  selector:
    app: openldap-demo
    tier: phpldapadmin-demo
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin-demo
  labels:
    app: openldap-demo
spec:
  selector:
    matchLabels:
      app: openldap-demo
      tier: phpldapadmin-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap-demo
        tier: phpldapadmin-demo
    spec:
      containers:
      - name: php-ldap-admin
        image: osixia/phpldapadmin:0.8.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: openldap
        ports:
        - containerPort: 443
