spring.profiles.active: svc1

spring.application.name: HELLO-SERVICE
eureka.instance.hostname: localhost

eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:${user.eureka.server.port}/eureka/