server.port: 8761

user.peer2.port: 8762

eureka.instance.hostname: localhost
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true

# Config eureka service url for eureka client
eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:${user.peer2.port}/eureka/

logging.level.com.netflix.eureka: OFF
logging.level.com.netflix.discovery: OFF
