spring.profiles.active: local
spring.cloud.refresh.enabled: false
travel-config.supportedDestinations: SWISSRE, BONORTE, CRETE, LONDON, PARIS
management.endpoints.web.base-path: "/"
management.endpoints.web.exposure.include: "*"
management.health.defaults.enable: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enable: false
  security:
    enable: false


